### ISSUE TITLE
Barco HDX projectors

### ISSUE THREAD

**Issue by ping141** [bitfocus/companion-module-barco-hdx#1]
**Describe the feature**
Ability to control basic or medium advanced features on HDX series projectors. Lamp on/off, test patterns on/off etc.

**Is this platform dependent (windows, mac, ..)?**
Win, Mac, Linux

**If documentation is required to implement, do you know where to find it?**
Not sure...

**Usecases**
Would make a great remote control feature for projectors which will enable other stage crew than the video dept. to do basic projector tasks.

**Comment by alatteri** [comment]
I have this https://www.barco.com/en/product/dp4k-p projector, but hopefully it uses the same protocol as HDX. I'll try it.

**Comment by alatteri** [comment]
Tested it on my projector, couldn't get it to do anything.  But I don't have an HDX, I have a cinema projector.

**Comment by JeffreyDavidsz** [comment]
@alatteri looking at the docu, the cinema projectors need to use the communicator software. I'll check with Barco if direct communication is possible.

**Comment by JeffreyDavidsz** [comment]
So I checked with Barco. The TCP/IP or external commands are not available for public (cinema projectors). You might be able to reverse engineer some commands?

**Comment by haakonnessjoen** [comment]
@alatteri If you capture network traffic with wireshark while you control one command at a time, and save each dump from what command you used. And we could look at reverse engineering the protocol, unless you are up for it yourself.

**Comment by alatteri** [comment]
> So I checked with Barco. The TCP/IP or external commands are not available for public (cinema projectors). You might be able to reverse engineer some commands?

@JeffreyDavidsz    The R59770483-24-CommunicatorPCversionforDP2K-andDP4K-series.pdf file I uploaded is a portion right out of the cinema projector manual.  It seems to have automation commands specified.

**Comment by alatteri** [comment]
> @alatteri If you capture network traffic with wireshark while you control one command at a time, and save each dump from what command you used. And we could look at reverse engineering the protocol, unless you are up for it yourself.

I won't be able to try this until late next week.

**Comment by JeffreyDavidsz** [comment]
@alatteri PROJECTOR.Turn Lamp Off could be something. But missing port numbers TCP/UDP? Try to telnet to your projector the above command. If that works create a new issue here for your projector as this was originally for hdx. I'll be happy the implement the other 4/5 options for you

**Comment by alatteri** [comment]
The commands don't seem to do anything, and none of our web UI logins work with the telnet.

Enceladus:~ alan$ telnet 192.168.113.4 43680
Trying 192.168.113.4...
Connected to communicator.video.instinctual.studio.
Escape character is '^]'.
PROJECTOR.Turn Lamp Off

telnet> Enceladus:~ alan$ telnet 192.168.113.4 43680
Trying 192.168.113.4...
Connected to communicator.video.instinctual.studio.
Escape character is '^]'.

Enceladus:~ alan$ telnet 192.168.113.4
Trying 192.168.113.4...
Connected to communicator.video.instinctual.studio.
Escape character is '^]'.
DP4K-P login: admin
Password: 
Login incorrect

**Comment by JeffreyDavidsz** [comment]
Sorry as said before, according to Barco this is a well kept secret. It is strange they post some stuff in a manual and of course you could reverse engineer the commands send by the software, but at this point I cannot help you any further.

**Comment by JeffreyDavidsz** [comment]
@alatteri as it looks Barco might give the protocol stay tuned. I'll create a new issue for the DP4K

**Comment by JeffreyDavidsz** [comment]
Barco HDX module is in now
