### ISSUE TITLE
Tested?

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-barco-hdx#4]
Is loadlayout tested and working? Because, looking at the code, all commands are sent in their binary form. But loadlayout is sent as a hex string (because of toString(‘hex’). And that seems weird?

**Comment by JeffreyDavidsz** [comment]
Nope, I don't have confirmation yet. On both types. My guess is that the binary one will work but the loadlayout doesn't. Waiting to get confirmation, so I can make both equal.

**Comment by ping141** [comment]
Hi! Lamp on works. But after that, neither lamp off nor shutter functions work. I have tested on HDX and HDF Laser.

**Comment by JeffreyDavidsz** [comment]
Hi @ping141 thx for testing, just tell be sure did you use a build of today?

**Comment by ping141** [comment]
i did. or at least i think i did. let me check

**Comment by ping141** [comment]
...1457. downloaded today.

**Comment by JeffreyDavidsz** [comment]
There is a 1455 and one of this morning, but I'm not quite sure when I made the change

**Comment by JeffreyDavidsz** [comment]
Would you be able to test the barco-dp module on your hdx? Don't know if shift focus zoom will work but I'm interested in the lamp and shutter

**Comment by ping141** [comment]
I got this...

![error](https://user-images.githubusercontent.com/44139963/56804845-5aecea80-6827-11e9-943f-12919699b265.PNG)

**Comment by JeffreyDavidsz** [comment]
Yep seeing where that came from, as of tomorrow I've got some udx on my hand, I'll play with them to see what kind of info they need. The commands are fine but me sending them not ;-) I'll keep this updated

**Comment by willosof** [comment]
UDXes is entirely different. The pulse platform has a new JSON API :)

But Hdx hdf and hdq should be similar afaik.

**Comment by JeffreyDavidsz** [comment]
Dp projectors have the same structure but I'm trying to figure out if I need to send the Buffer or Buffer.toString('hex').

**Comment by JeffreyDavidsz** [comment]
@ping141 if you have the time, in the barco-dp module the shutter open/close sends the command in to different ways. could you report back which one works? It's being build as we speak.

**Comment by alatteri** [comment]
@JeffreyDavidsz  I left some feedback in the DP module.  Tested lamp and shutter functions on a DP4K-P.  Neither seemed to do anything.

**Comment by ping141** [comment]
@JeffreyDavidsz It took some time, I didn't bring the HDX home for the weekend... :) Still want me to test these things?

**Comment by JeffreyDavidsz** [comment]
Please do, tnx one of the shutter options should work

**Comment by ping141** [comment]
Got a connection error on "series 2". "Series 1" didn´t work.

**Comment by JeffreyDavidsz** [comment]
No please test the hdx module, I rewrote the dp one for dp projectors this weekend :-)

**Comment by ping141** [comment]
None of them work here. I had 3 options.

**Comment by JeffreyDavidsz** [comment]
Tnx for testing @ping141 now it works. I'll add some more. For now I'll close this
